In [ ]:
#Get the datasets
!wget -q https://github.com/jomokojomoko/CISCASSIGNMENT/raw/main/Video_games_esrb_rating.csv
!wget -q https://github.com/jomokojomoko/CISCASSIGNMENT/raw/main/test_esrb.csv


In [ ]:
#Process the datasets into training and testing
import pandas as pd
import csv
from sklearn import preprocessing
from keras.utils import np_utils
#Get testing and training datasets
xy_train_df = pd.read_csv('Video_games_esrb_rating.csv',error_bad_lines=False)
test=pd.read_csv('test_esrb.csv',error_bad_lines=False)
#Get X sets
xtrain=xy_train_df.drop(columns=['title','esrb_rating'])
xtest=test.drop(columns=['title','esrb_rating'])
#Get Y sets
ytrain=xy_train_df['esrb_rating']
ytest=test['esrb_rating']
print(ytrain)
#One Hot Encoding
le=preprocessing.LabelEncoder()
le.fit(ytrain)
ytrain=le.transform(ytrain)
ytest=le.transform(ytest)
yc=ytest
ytest=np_utils.to_categorical(ytest)
ytrain=np_utils.to_categorical(ytrain)
print(ytrain)
print(yc)

0        E
1       ET
2        M
3       ET
4        T
        ..
1890     M
1891     T
1892     E
1893     T
1894     E
Name: esrb_rating, Length: 1895, dtype: object
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 ...
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]
[3 0 3 0 1 2 2 1 0 3 3 3 1 3 3 2 2 3 0 1 3 1 1 3 1 1 0 3 2 1 3 1 1 3 3 3 2
 1 0 3 3 3 0 2 0 0 3 1 1 1 3 3 2 1 2 1 3 3 2 3 0 2 1 0 2 1 3 0 0 0 0 1 3 1
 3 1 3 2 0 0 3 3 3 1 0 2 2 3 1 1 0 1 3 3 3 0 1 1 1 3 0 0 3 2 2 0 2 3 3 3 3
 3 1 3 0 3 3 1 3 0 3 3 1 0 2 3 0 1 1 3 1 3 2 3 0 3 3 0 3 3 0 3 3 3 2 3 2 3
 1 1 1 0 1 3 0 0 0 2 3 3 1 1 1 0 2 0 2 0 1 3 2 1 3 3 2 0 2 3 1 2 2 3 3 3 0
 3 1 2 1 3 0 0 1 1 3 3 2 3 0 3 0 0 3 3 3 1 3 0 1 2 3 3 0 3 2 0 3 0 3 1 3 3
 2 0 3 0 3 0 2 2 3 2 2 3 2 0 3 1 0 0 0 1 1 1 2 2 1 2 1 3 3 1 0 2 1 3 0 3 1
 3 1 1 2 2 1 3 3 3 3 2 0 3 0 2 3 1 1 0 2 1 2 1 0 3 3 0 3 3 1 3 3 2 1 1 3 2
 1 1 1 1 3 1 0 3 1 3 3 0 0 0 3 3 3 0 3 3 0 3 1 0 2 3 1 3 2 0 0 2 1 3 2 2 3
 3 3 1 2 3 0 3 2 3 3 2 3 0 1 2 2 3 3 1 1 3 0 2 2 3 3 2 1 1 0 

In [ ]:
#Neural Network Model
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense, Dropout, Input

#Function to build a model
def build():
    #Defindes the shape of the input
    #The shape is 32 arttibutes
    img_in = Input(shape=(32))

    #Activation layers
    fc1 = Dense(200)(img_in) 
    fc2 = Dense(200,activation="relu")(fc1)
    fc3 = Dense(200)(fc2)
    fc4 = Dense(200,activation="relu")(fc3)
    fc5 = Dense(200)(fc4)
    #final layor using softmax activation function  with 4 ouput
    output = Dense(4, activation = 'softmax')(fc5)
    #Creates a keras model defining the input, and output
    model = tf.keras.Model(inputs=img_in, outputs=output)
    return model


model = build()
#Configuring the model for training
#Uses the Adam model for optimization
#Calculates loss with categorical cross entropy
#The metrics used for validation in this model is accuracy
model.compile(
        loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']
        )

model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 32)]              0         
_________________________________________________________________
dense (Dense)                (None, 200)               6600      
_________________________________________________________________
dense_1 (Dense)              (None, 200)               40200     
_________________________________________________________________
dense_2 (Dense)              (None, 200)               40200     
_________________________________________________________________
dense_3 (Dense)              (None, 200)               40200     
_________________________________________________________________
dense_4 (Dense)              (None, 200)               40200     
_________________________________________________________________
dense_5 (Dense)              (None, 4)                 804   

In [ ]:
epochs = 10
batch_size = 64

#Fitting the model with the training set
#Fitting the models batch size
#10 epochs
#0.3 of the data will be used to validate the model
history = model.fit(x = xtrain,
                    y = ytrain,
                    batch_size = batch_size,
                    validation_split=0.3,
                    epochs=epochs
                    )

Epoch 1/10
21/21 [==============================] - 1s 27ms/step - loss: 1.0154 - accuracy: 0.5763 - val_loss: 0.3849 - val_accuracy: 0.8699
Epoch 2/10
21/21 [==============================] - 0s 5ms/step - loss: 0.4070 - accuracy: 0.8357 - val_loss: 0.3381 - val_accuracy: 0.8682
Epoch 3/10
21/21 [==============================] - 0s 6ms/step - loss: 0.3592 - accuracy: 0.8461 - val_loss: 0.2956 - val_accuracy: 0.8910
Epoch 4/10
21/21 [==============================] - 0s 6ms/step - loss: 0.3059 - accuracy: 0.8828 - val_loss: 0.2896 - val_accuracy: 0.8893
Epoch 5/10
21/21 [==============================] - 0s 6ms/step - loss: 0.3045 - accuracy: 0.8790 - val_loss: 0.3081 - val_accuracy: 0.8787
Epoch 6/10
21/21 [==============================] - 0s 6ms/step - loss: 0.3244 - accuracy: 0.8579 - val_loss: 0.2894 - val_accuracy: 0.8735
Epoch 7/10
21/21 [==============================] - 0s 5ms/step - loss: 0.2864 - accuracy: 0.8868 - val_loss: 0.2875 - val_accuracy: 0.8963
Epoch 8/10
21/21 [=

In [ ]:
#Evaluate the model
print("Evaluate on test data")
results = model.evaluate(xtest, ytest, batch_size=64)
print("test loss, test acc:", results)



Evaluate on test data
8/8 [==============================] - 0s 2ms/step - loss: 0.4765 - accuracy: 0.8500
test loss, test acc: [0.47647467255592346, 0.8500000238418579]


In [ ]:
#Get the confusion matrix
import numpy as np
from sklearn.metrics import confusion_matrix
ypred=model.predict(xtest)
rounded=np.argmax(ypred, axis=-1)
confusion = confusion_matrix(yc,rounded)
print(confusion)

[[ 95   4   0   1]
 [  4 112   1   9]
 [  0   0  72  18]
 [  2  21  15 146]]
